# Import Tensorflow

In [32]:
import tensorflow as tf

print(tf.__version__)


2.13.0


<tf.Tensor: shape=(), dtype=int32, numpy=7>

# Creating tensors with tf.constant()

In [33]:
# Creating a scalar tensor with tf.constant()
scalar = tf.constant(7)
print(scalar)

# Check the number of dimensions of a tensor (ndim)
scalar.ndim

tf.Tensor(7, shape=(), dtype=int32)


0

In [9]:
# Create a vector
vector = tf.constant([10, 10])
print(vector)
print('num dimensions', vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32)
num dimensions 1


In [10]:
# Create a matrix
matrix = tf.constant([[1, 2], [2,3], [4, 5], [6,7]])
print(matrix)
print('num dimensions', matrix.ndim)

tf.Tensor(
[[1 2]
 [2 3]
 [4 5]
 [6 7]], shape=(4, 2), dtype=int32)
num dimensions 2


In [13]:
# Create a matrix with a specified data type
another_matrix = tf.constant([[1.0, 2.0], [3.0, 4.0]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

In [14]:
another_matrix.ndim

2

In [17]:
# Create a tensor
tensor_3d = tf.constant([
    [
        [1, 2],
        [2, 3]
    ],
    [
        [4, 5],
        [6, 7]
    ]
])
tensor_3d

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)>

In [18]:
tensor_3d.ndim

3

In [19]:
# 0 dimensional tensor is a scalar
# 1 dimensional tensor is a vector
# 2+ dimensional tensor is a matrix

# Creating tensors with tf.Variable()

In [21]:
# Creating tensors with tf.Variable() as above
# tf.constant() creates an immutable tensor
# tf Variable() creates a mutable tensor
scalar = tf.Variable(7)
scalar

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>

In [22]:
vector = tf.Variable([1, 2])
vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [23]:
matrix = tf.Variable([[1, 2], [2, 3]])
matrix


<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [2, 3]], dtype=int32)>

In [24]:
matrix[0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [25]:
matrix[0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [26]:
matrix[0].assign([5, 6])
matrix

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 6],
       [2, 3]], dtype=int32)>

In [30]:
matrix[1].assign([200, 300])
matrix

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[  5,   6],
       [200, 300]], dtype=int32)>

# Creating random tensors

In [36]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [39]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [41]:
random_1 == random_2 # they are the same because we used the same random seed

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [44]:
random_gen = tf.random.Generator.from_seed(42)
random_a = random_gen.normal(shape=(3,2))
random_b = random_gen.normal(shape=(3,2))
random_a, random_b, random_a == random_b


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.17522676,  0.71105534],
        [ 0.54882437,  0.14896014],
        [-0.54757965,  0.61634356]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

# Shuffle the order of elements in a tensor

In [45]:
not_shuffled = tf.constant([[1, 2], [2, 3], [3, 4]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [3, 4]], dtype=int32)>

In [54]:
shuffled = tf.random.shuffle(not_shuffled) # without seed it's different every time. we can use seed={num} to ensure the same shuffle every time
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [3, 4]], dtype=int32)>

## Global seed applies to all random generations

In [50]:
tf.random.set_seed = 42 # this s

## local seed applies to the individual function call

In [55]:
shuffled = tf.random.shuffle(not_shuffled, seed=59)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [2, 3]], dtype=int32)>