# Getting information from tensors
Shape

Rank : Number of tensor dimensions. E.g. scalar is rank 0. Vector is rank 1, etc.

Axis or dimension : A particulr dimension of a tensor

Size: The total number of values in the tensor

Data Type

In [ ]:
import tensorflow as tf
vector = tf.constant([1, 2, 3 , 4])
vector.shape

TensorShape([4])

In [ ]:
vector.ndim # number dimensions

1

In [ ]:
tf.size(vector) # size is 4 because there are 4 values; therefore numpy=4

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
tf.size(vector).numpy()

4

In [ ]:
tf.rank(vector) # rank is 1 because it's one dimensional;  therefore numpy=1

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.rank(vector).numpy()

1

In [ ]:
vector.dtype

tf.int32

# Indexing tensors

In [ ]:
# value at first index
vector[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
# value at the last index
vector[-1]

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
matrix = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
matrix.shape

TensorShape([2, 2, 3])

In [ ]:
matrix[0]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
matrix[:1] # up to the first index

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
matrix[:1, :1] # reduces the first dimension to a shape of 1 and reduces the shape of the second dimension to 1 but preserves the entire third dimension

<tf.Tensor: shape=(1, 1, 3), dtype=int32, numpy=array([[[1, 2, 3]]], dtype=int32)>

In [ ]:
matrix[0, 0] # notice the difference in shapes and values between [:1, :1] and [0, 0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
matrix[:1, : , :1] # reduce the shapes of the first and third dimension to 1 but kee the second dimension as is

<tf.Tensor: shape=(1, 2, 1), dtype=int32, numpy=
array([[[1],
        [4]]], dtype=int32)>

In [ ]:
matrix[:, :, -1] # extract last value of the third dimension

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  6],
       [ 9, 12]], dtype=int32)>