## SavedModel Format

In [5]:
import tensorflow as tf
import numpy as np

model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(1,)),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(1, activation=None)
])

model.compile(loss=tf.keras.losses.mean_absolute_error,
              optimizer=tf.keras.optimizers.SGD(),
              metrics=['mae'])
X = tf.range(-100, 100, 5)
y = X + 10
X, y

(<tf.Tensor: shape=(40,), dtype=int32, numpy=
 array([-100,  -95,  -90,  -85,  -80,  -75,  -70,  -65,  -60,  -55,  -50,
         -45,  -40,  -35,  -30,  -25,  -20,  -15,  -10,   -5,    0,    5,
          10,   15,   20,   25,   30,   35,   40,   45,   50,   55,   60,
          65,   70,   75,   80,   85,   90,   95], dtype=int32)>,
 <tf.Tensor: shape=(40,), dtype=int32, numpy=
 array([-90, -85, -80, -75, -70, -65, -60, -55, -50, -45, -40, -35, -30,
        -25, -20, -15, -10,  -5,   0,   5,  10,  15,  20,  25,  30,  35,
         40,  45,  50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100,
        105], dtype=int32)>)

In [7]:
X = tf.expand_dims(X, axis=-1)
model.fit(X, y, epochs=10, verbose=0)

In [11]:
model.save("./simple_model.h5")

## Loading the model

In [17]:
new_model = tf.keras.models.load_model('/content/simple_model.h5')
new_model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 100)               200       
                                                                 
 dense_3 (Dense)             (None, 1)                 101       
                                                                 
Total params: 301 (1.18 KB)
Trainable params: 301 (1.18 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [22]:
model.predict([17])[0][0], new_model.predict([17])[0][0]

1/1 [==============================] - 0s 67ms/step


(4.366289, 4.366289)

## Downloading the Model

1. Right-Click on the file and choose Download
2. Use code (see cell below)
3. Use Google Drive (see second cell below)

In [23]:
from google.colab import files
files.download('/content/simple_model.h5')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [26]:
# Copy a file from Colab to Google Drive
!cp /content/simple_model.h5 /content/drive/MyDrive/Colab\ Notebooks/Tensorflow\ Certification\ Prep/