In [3]:
import tensorflow as tf
import numpy as np

## Create a tensor from a NumPy array

In [4]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

## Create a NumPy array from a tensor
Remember: Tensors are much faster on a GPU or TPU than NumPy arrays.

In [5]:
np.array(J)

array([ 3.,  7., 10.])

In [6]:
# alternatively
J.numpy()

array([ 3.,  7., 10.])

In [7]:
# you can get values easily to manipulate and add back into the tensor
J.numpy()[1]


7.0

In [8]:
# important: numpy inputs can have a different data type than direct inputs. See below.
direct_input = tf.constant([3., 7., 10.])
direct_input.dtype

tf.float32

In [9]:
numpy_array = np.array([3., 7., 10.])
numpy_input = tf.constant(numpy_array)
numpy_input.dtype

tf.float64